### ISSUE TITLE
[M16] [Meatinfo] Блок 'Посмотрите похожие предложения'

### ISSUE THREAD

**Issue by devsuperstars** [devsuperstars/design#1]
https://vladimir.meatinfo.ru/trade/golovy-svinye-shkurku-svinuyu-schekovinu-123938
Текущий Посмотрите похожие предложения' выглядит так:
![image](https://user-images.githubusercontent.com/51328479/75544121-5f2ff880-5a34-11ea-9ea8-6ba93e62530f.png)
Каждый подблок содержит: цену, картинку, регион, заголовок.

Необходимо предложить для декстопной версии, мобильной и планшетов:
1) Более чистый дизайн с растяжением на длину контейнера и динамическим количеством подблоков. Очевидно что мобильная версии вместит меньшее количество подблоков чем дестопная.
2) Необходимо этот блок визуально выделить более сильно чем само объявление т.к. он показывается в объявлениях которые давно не поднимались (более 3-х месяцев).

**Цель чтобы страница не была тупиковой!**

**Comment by KochkinaY** [comment]
Вопросы:
1. Почему "похожие предложения" выводятся перед основным объявлением?
2. Что подразумевается под "динамическим количеством подблоков"? Их количество будет меняться?
3. "Цель чтобы страница не была тупиковой!" - этот тезис тоже не совсем понятен.
4. Какие блоки останутся в мобильной и планшетной версии, а какие уйдут?

**Comment by timatrue** [comment]
@KochkinaY 
1.  "похожие предложения" выводятся перед текстом объявления потому что объявление не обновлялось владельцем уже 3 месяца. Т.е. оно не актуальное. Наша задача предложить пользователю, который его открыл, более релевантный контент с помощью блока 'похожие предложения'. 
2. "динамическим количеством подблоков" - означает что в зависимости от разрешения экрана мы можем выводить разное количество 'похожих предложений'.
3. "Цель чтобы страница не была тупиковой!"  - наша задача удержание пользователя если он видит что объявление которое он просматривает уже не актуально. Мы предполагаем что если в блоке 'Похожие предложения' будет релевантный контент то самое главное чтобы пользователь увидел этот блок. Визуально можно сделать это следующим образом: затемнить основной блок с контентом. Пример:

![image](https://user-images.githubusercontent.com/20603944/75765914-58192b00-5d51-11ea-9899-6e52c99d3dce.png)

4.   в мобильной версии мы уже обрезали все что можно. если зайдешь с мобильного то увидешь следующую картину:
![image](https://user-images.githubusercontent.com/20603944/75765429-8d714900-5d50-11ea-989f-15382b794ed6.png)

**Comment by KochkinaY** [comment]
![1920](https://user-images.githubusercontent.com/35227008/76864619-72cfc180-6872-11ea-8992-7b1ca3665200.png)
![tablet](https://user-images.githubusercontent.com/35227008/76864630-75cab200-6872-11ea-81a8-0e6f3dd7acc5.png)
![mobile](https://user-images.githubusercontent.com/35227008/76864636-782d0c00-6872-11ea-96d5-6d929936fbcf.png)

**Comment by KochkinaY** [comment]
[meatinfo.zip](https://github.com/devsuperstars/design/files/4343843/meatinfo.zip)


Комментарии:
1. В мобильной версии можно раскрывать (разворачивать) и сворачивать "предложения".
Например, выводить сначала только 2 предложения.

**Comment by KochkinaY** [comment]
2. Какая иерархия у полей карточки объявления? Что за чем важно выводить: сначала заголовок, потом цену и потом локацию? По какой логике похожие предложения подтягиваются к основному? Цена не кликабельна?

**Comment by timatrue** [comment]
>     1. Какая иерархия у полей карточки объявления? Что за чем важно выводить: сначала заголовок, потом цену и потом локацию? По какой логике похожие предложения подтягиваются к основному? Цена не кликабельна?

- сначала заголовок, потом  локацию,  потом цену
- цена, заголовок кликабельна и ведет на объявление. Регион не кликабельный.
- 'похожие предложения' подбираются парсером. парсер ищет аналогичную продукцию в других объявлениях в этом же регионе. Если объявление найдено то проверяется чтобы в нем была картинка и цена. Если таких объявлений нету то парсер ищет в соседних регионах. Если аналогов вообще нету то парсер показывает рекламное объявление.

**Comment by timatrue** [comment]
По текущему дизайну:
- у нас нету возможности выводить картинки в прямоугольном формате (потом сделаем). Можно показать пример как это будет выглядить с квадратными картинками?
- оставляем mobile2. mobile1 -нет
- добавляем плашку 'Объявление было актуально до ДАТА' (пример приложил)
![image](https://user-images.githubusercontent.com/20603944/76956387-0366da00-6925-11ea-9b00-abff5f1a8247.png)

- кнопку позвонить - добавить имя (пример приложил)
![image](https://user-images.githubusercontent.com/20603944/76956147-89ceec00-6924-11ea-9ce2-dd4fbb661726.png)

**Comment by KochkinaY** [comment]
[meatinfo.zip](https://github.com/devsuperstars/design/files/4365724/meatinfo.zip)

**Comment by timatrue** [comment]
@KochkinaY 
1) добавь плиз [реальные картинки](https://peterburg.meatinfo.ru/trade/govyadina-kolbasy-i-delikatesy-184446) вместо красивых.
2) нету плашки  'Объявление было актуально до ДАТА' на декстопной версии.

**Comment by KochkinaY** [comment]
[meatinfo.zip](https://github.com/devsuperstars/design/files/4393336/meatinfo.zip)
